<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SALE</name>
   <tag></tag>
   <elementGuidId>846a2797-9065-4563-9e95-f20ad738fd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-sale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li[3]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9043524b-ee09-4e4a-98dc-839f2caec745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-sale</value>
      <webElementGuid>6b8ba8b6-c57f-475c-89b3-e3274a4ed7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            SALE
          </value>
      <webElementGuid>76b0a65f-baf4-4ea2-ad66-c7bc02874f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/div[2]/div[@class=&quot;header-wrapper&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;page-width&quot;]/div[@class=&quot;header-layout header-layout--right header-layout--mobile-logo-only&quot;]/div[@class=&quot;header-item header-item--navigation text-right small--hide&quot;]/ul[@class=&quot;site-nav site-navigation small--hide&quot;]/li[@class=&quot;site-nav__item site-nav__expanded-item&quot;]/a[@class=&quot;site-nav__link&quot;]/div[@class=&quot;menu-sale&quot;]</value>
      <webElementGuid>2f9819c8-464a-4982-a67f-833a82c232c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li[3]/a/div</value>
      <webElementGuid>22ce195d-3396-4f03-8f86-8d1bd45f9d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[2]/following::div[1]</value>
      <webElementGuid>860871db-68c5-403b-97d0-008179330134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pants'])[2]/following::div[1]</value>
      <webElementGuid>d0370294-e269-40f6-a526-1f87efe5f764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLLECTIONS'])[1]/preceding::div[1]</value>
      <webElementGuid>b8a44b2a-c122-4317-80df-640295865899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mezzala'])[2]/preceding::div[1]</value>
      <webElementGuid>3fec56cc-f13d-4a72-ab7d-b6117555f8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div</value>
      <webElementGuid>99e2de4a-4cf6-4223-9d96-ea08094b5273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
            SALE
          ' or . = '
            SALE
          ')]</value>
      <webElementGuid>8f473acb-093b-4031-945f-bb1c746bb747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
