<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show_customerLogin</name>
   <tag></tag>
   <elementGuidId>62b2bc49-1261-412f-9f34-ce0881404d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f84c18a-cbd7-4bbe-8f4f-c43b15c1ae83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>809a5fdf-6866-46b2-a0e9-038b9d4eba00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--full</value>
      <webElementGuid>2b867c14-be4b-4a2c-8478-8610d2760be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerLogin</value>
      <webElementGuid>3de2353a-3c00-492b-8794-5d2c33037259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>23701407-2076-4892-9fce-d7b93f721bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerLogin&quot;)</value>
      <webElementGuid>10323e50-f879-45e7-9ae0-78dec66946a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerLogin']</value>
      <webElementGuid>a5ca327e-6194-40ea-a57b-871748c39915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/p/input</value>
      <webElementGuid>d0de984e-dc5b-4807-a99c-2197eb0b783b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>fecc98f1-0d3a-4b48-aa8d-c26d4571efa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'customerLogin']</value>
      <webElementGuid>c7efe0c0-5179-47a3-b299-4b25cf24394a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
