<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot_customerpassword</name>
   <tag></tag>
   <elementGuidId>db05c823-04c6-452f-8bb6-af4da2338b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebbba964-c8fe-4193-98bb-2938d69a6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c5d13787-bdf1-4d79-8bfb-7add1474b3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[password]</value>
      <webElementGuid>6c1d7962-724b-491e-b1cc-6dcfa652bbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPassword</value>
      <webElementGuid>1baa6011-1424-46fd-a30f-b97d28364c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-full</value>
      <webElementGuid>8c487c56-2883-45fb-a821-2af7656904cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerPassword&quot;)</value>
      <webElementGuid>75fccbf9-1a52-4023-a314-506b5cb0c35c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerPassword']</value>
      <webElementGuid>eaff8356-4f55-444e-a492-85093e69b3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[2]/input</value>
      <webElementGuid>63935343-973d-4ab9-816b-67264b808b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>62fe0815-7bc2-4c4f-8f91-c9529d9eb6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'customer[password]' and @id = 'CustomerPassword']</value>
      <webElementGuid>a7d78ac0-d3cb-4246-95a4-efc2002fb2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
